// Ventana 800x600
package ventanasTicTacToe;

/**
 *
 * @author sebassvr
 */
public class VentanaInicial extends javax.swing.JFrame {
    private String usuario1;
    private String usuario2;
    
    public VentanaInicial() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        etiquetaTitulo = new javax.swing.JLabel();
        etiquetaNombre1 = new javax.swing.JLabel();
        etiquetaNombre2 = new javax.swing.JLabel();
        cajaNombre1 = new javax.swing.JTextField();
        cajaNombre2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        botonGuardar = new javax.swing.JButton();
        etiquetaMuestra1 = new javax.swing.JLabel();
        etiquetaMuestra2 = new javax.swing.JLabel();
        botonComenzarJuego = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiquetaTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tituloTresenRaya.png"))); // NOI18N
        panel.add(etiquetaTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        etiquetaNombre1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        etiquetaNombre1.setText("Usuario1:");
        panel.add(etiquetaNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 209, -1, -1));

        etiquetaNombre2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        etiquetaNombre2.setText("Usuario2:");
        panel.add(etiquetaNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 263, -1, -1));

        cajaNombre1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        panel.add(cajaNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 210, 411, 35));

        cajaNombre2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        panel.add(cajaNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 264, 411, 35));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tresEnRaya.gif"))); // NOI18N
        panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 411, -1, -1));

        botonGuardar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        botonGuardar.setText("GUARDAR");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });
        panel.add(botonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 323, -1, -1));

        etiquetaMuestra1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        panel.add(etiquetaMuestra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, 469, -1));

        etiquetaMuestra2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        panel.add(etiquetaMuestra2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 540, 469, -1));

        botonComenzarJuego.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        botonComenzarJuego.setText("COMENZAR JUEGO");
        botonComenzarJuego.setVisible(false);

        botonComenzarJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonComenzarJuegoActionPerformed(evt);
            }
        });
        panel.add(botonComenzarJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 357, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        usuario1 = cajaNombre1.getText();
        usuario2 = cajaNombre2.getText();
        // En caso de que haya una caja vacia, automaticamente se asignara un nombre por default.
        if (usuario1.isEmpty()|| usuario2.isEmpty()) {
            if (usuario1.isEmpty()) {
                usuario1 = "Usuario1";
            }
            if (usuario2.isEmpty()) {
                usuario2 = "Usuario2";
            }
            
            botonGuardar.setVisible(false);
            etiquetaMuestra1.setText(usuario1+" color azul, tiene 1er turno.");
            etiquetaMuestra2.setText(usuario2+" color café claro, tiene 2do turno.");
            botonComenzarJuego.setVisible(true);
        }
        else{
            botonGuardar.setVisible(false);
            etiquetaMuestra1.setText(usuario1+" color azul, tiene 1er turno.");
            etiquetaMuestra2.setText(usuario2+" color café claro, tiene 2do turno.");
            botonComenzarJuego.setVisible(true);
        }
        // Desabilitamos la caja de nombres para que el usuario no pueda cambiar el texto.
        cajaNombre1.setEnabled(false);
        cajaNombre2.setEnabled(false);
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void botonComenzarJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonComenzarJuegoActionPerformed
        VentanaPrincipal ventanaP = new VentanaPrincipal(usuario1, usuario2);
        ventanaP.setVisible(true);
        
        // Cerramos esta ventana.
        dispose();
    }//GEN-LAST:event_botonComenzarJuegoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonComenzarJuego;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JTextField cajaNombre1;
    private javax.swing.JTextField cajaNombre2;
    private javax.swing.JLabel etiquetaMuestra1;
    private javax.swing.JLabel etiquetaMuestra2;
    private javax.swing.JLabel etiquetaNombre1;
    private javax.swing.JLabel etiquetaNombre2;
    private javax.swing.JLabel etiquetaTitulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
